import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';
import { Providers } from '@/src/shared/providers/providers';
import './globals.css';

const questrial = Urbanist({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-questrial',
});

export const metadata: Metadata = {
  title: 'Inking',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased ${questrial.variable}`}>
      <body className="min-h-full flex flex-col font-sans">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
