/**
 * Stable machine-readable error codes returned to API clients.
 *
 * These codes are part of the public API contract. Never change or remove an
 * existing value without a coordinated frontend/contract release.
 */
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_OAUTH_STATE: 'INVALID_OAUTH_STATE',
  OAUTH_PROVIDER_ERROR: 'OAUTH_PROVIDER_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  COMPILER_ERROR: 'COMPILER_ERROR',
  COMPILER_TIMEOUT: 'COMPILER_TIMEOUT',
  COMPILER_UNAVAILABLE: 'COMPILER_UNAVAILABLE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
